Update to Advance Steel 2024, AutoCAD 2024, Dynamo Core 2.17.0
DynamoDS/Dynamo-Advance-Steel pull request #81
Opened 2023-02-06 15:24 UTC by CristianUdreaADSK

* Updated Dynamo Extension for Advance Steel to work with Dynamo Core 2.17.0 and AutoCAD 2024
* Updated sample scripts to replace obsolete nodes with up to date ones
* Code changes to fix obsolete API errors & warnings

2023-02-06 15:39 UTC, vpavel04 requested changes

2023-02-06 15:39 UTC, vpavel04 commented on src/DynamoAdvanceSteelInstall/Product.wxs
> -	<Product Id="{64B3F114-4E02-4AE8-B55F-127D9694CBBA}" Name="Dynamo Extension for Autodesk Advance Steel 2023" Language="1033" Version="1.0.0.0" Manufacturer="Autodesk" UpgradeCode="{6A1B06FE-4364-4E5
the product guid must be regenerated

2023-02-06 18:57 UTC, CristianUdreaADSK commented on src/DynamoAdvanceSteelInstall/Product.wxs
> -	<Product Id="{64B3F114-4E02-4AE8-B55F-127D9694CBBA}" Name="Dynamo Extension for Autodesk Advance Steel 2023" Language="1033" Version="1.0.0.0" Manufacturer="Autodesk" UpgradeCode="{6A1B06FE-4364-4E5
please check the latest commit

2023-02-07 07:08 UTC, vpavel04 approved these changes

2023-02-09 07:01 UTC, vpavel04 approved these changes

2023-02-09 07:07 UTC, merged